# Generated by Django 3.2a1 on 2021-01-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Repuestos.marcaauto')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRepuesto', models.TextField(max_length=60)),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=13)),
                ('descripcion', models.TextField(max_length=200)),
                ('stock', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Repuestos.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Repuestos.marcaauto')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Repuestos.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Partes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=60)),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=13)),
                ('descripcion', models.TextField(max_length=200)),
                ('stock', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('nombreRepuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Repuestos.repuesto')),
            ],
        ),
    ]
