# Generated by Django 3.2a1 on 2021-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0002_comuna_localidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localidades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
