# Generated by Django 3.2a1 on 2021-02-10 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0005_auto_20210210_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partes',
            name='nombreRepuesto',
        ),
        migrations.RemoveField(
            model_name='marcaauto',
            name='parte',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Repuestos.marcaauto'),
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Localidades',
        ),
        migrations.DeleteModel(
            name='Partes',
        ),
    ]
