# Generated by Django 3.2a1 on 2021-02-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0006_auto_20210210_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='marca',
        ),
    ]
