# Generated by Django 3.2a1 on 2021-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0009_auto_20210217_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='repuesto/', verbose_name='Foto'),
        ),
    ]
